"""SQLite persistence, migrations, and repositories."""

from llama_profile_lab.db.connection import connect_database, transaction
from llama_profile_lab.db.database import Database
from llama_profile_lab.db.migrations import (
    Migration,
    MigrationError,
    discover_migrations,
    migrate,
    schema_version,
)
from llama_profile_lab.db.repositories import (
    AcceleratorDeviceRepository,
    BenchmarkCaseRepository,
    BenchmarkRunRepository,
    CandidateRepository,
    DeploymentCandidateRepository,
    DeploymentPlanRepository,
    DeploymentPlacementRepository,
    DeploymentRunRepository,
    EnvironmentRepository,
    ExperimentRepository,
    MeasurementPolicyRepository,
    MemoryEstimateRepository,
    PlacementRepository,
    SearchSpaceRepository,
    ServerValidationRepository,
    TelemetryRepository,
    WorkloadCaseRepository,
    WorkloadSuiteRepository,
)

__all__ = [
    "AcceleratorDeviceRepository",
    "BenchmarkCaseRepository",
    "BenchmarkRunRepository",
    "CandidateRepository",
    "Database",
    "DeploymentCandidateRepository",
    "DeploymentPlanRepository",
    "DeploymentPlacementRepository",
    "DeploymentRunRepository",
    "EnvironmentRepository",
    "ExperimentRepository",
    "MeasurementPolicyRepository",
    "MemoryEstimateRepository",
    "PlacementRepository",
    "Migration",
    "MigrationError",
    "SearchSpaceRepository",
    "ServerValidationRepository",
    "TelemetryRepository",
    "WorkloadCaseRepository",
    "WorkloadSuiteRepository",
    "connect_database",
    "discover_migrations",
    "migrate",
    "schema_version",
    "transaction",
]
